export default {
  LOADING: 'LOADING_HOME',
  FETCH_POPULER: 'FETCH_POPULER_HOME',
  FETCH_ANIME_SEASON_NOW: 'FETCH_ANIME_SEASON_NOW_HOME',
  FETCH_GENRE: 'FETCH_GENRE_HOME',
  FETCH_ANIME_LIST: 'FETCH_ANIME_LIST_HOME',
};
